version: '3'
services:
    web:
      build: ./src/
      ports:
        - "49000:8080"
      command: npm start
      volumes:
        - ./src/:/app
        - /app/node_modules
      depends_on:
        - "db"
    db:
      build: ./mbslave-docker/
      restart: always
      ports:
        - "5432:5432"
volumes:
  logvolume01: {}
